### ISSUE TITLE
[DaMa] Fontbakery checks: Google Fonts glyph coverage

### ISSUE THREAD

**Issue by pablogamezDaMa** [balsamiq/balsamiqsans#13]
ℹ️ This issue is related to [Dalton Maag's fork of Balsamiq](https://github.com/daltonmaag/balsamiqsans-gft).

This is the [latest GF Latin-Core glyphset](https://github.com/googlefonts/glyphsets/blob/main/GF_glyphsets/Latin/txt/nice-names/GF_Latin_Core.txt).

The following glyphs are flagged by _FontBakery_ and missing in the set at the moment:
`/Germandbls/Wacute/Wdieresis/Wgrave/Ygrave/wacute/wdieresis/wgrave/ygrave`

The following glyphs weren't flagged by _FontBakery_ but are missing:
`/periodcentered.loclCAT/periodcentered.loclCAT.case`

➡️ Would GF require this project to cover those? 
➡️ Catalan's periodcentered too, even if fontbakery didn't flag it?

**Comment by madig** [comment]
@m4rc1e Can you please weight in here?

**Comment by m4rc1e** [comment]
> ➡️ Would GF require this project to cover those?

If the previous fonts didn't have them and you were not contracted to complete this glyphset, I'll make an exception. If the contract states we expect these glyphs, then we'll need them
