### ISSUE TITLE
[DaMa] Fontbakery checks: Ensure fonts have ScriptLangTags declared on the 'meta' table

### ISSUE THREAD

**Issue by pablogamezDaMa** [balsamiq/balsamiqsans#14]
ℹ️ This issue is related to [Dalton Maag's for of Balsamiq](https://github.com/daltonmaag/balsamiqsans-gft).  

There is no 'meta' table and never was in this font.  
I checked other big GF projects (Roboto) and those also miss a 'meta' table. 

➡️ Is a 'meta' table required?

**Comment by madig** [comment]
@m4rc1e Can you please weight in here?

**Comment by m4rc1e** [comment]
If the report is just a warn, we can skip it. This seems like a nicety.
