### ISSUE TITLE
[DaMa] Fontbakery checks: Check if each glyph has the recommended amount of contours

### ISSUE THREAD

**Issue by pablogamezDaMa** [balsamiq/balsamiqsans#15]
ℹ️ This issue is related to [Dalton Maag's fork of Balsamiq](https://github.com/daltonmaag/balsamiqsans-gft).

How strict is GF on this?  
The current contour set up is alright and meeting _Fontbakery's_ expectations would mean quite some manual work and little to no difference in results.

**Comment by madig** [comment]
@m4rc1e Can you please weight in here?

**Comment by m4rc1e** [comment]
If the reported glyphs look visually ok, then I'm happy. We usually use this test to detect if there's a missing quote mark from quotedbl etc.
