### ISSUE TITLE
Some small latin extended characters are in caps (or size issue)

### ISSUE THREAD

**Issue by boydkelly** [balsamiq/balsamiqsans#8]
Hi,
I keep a list of all the fonts that we can use here in West Africa for Mande languages and Balsamiq Sans is on the list.

https://coastsystems.net/blog/en/blog/2020-08-26-fontlist/

However if you note here, the extended latin characters are not in proportion seemingly in caps.

These are the symbols having a problem:

Glyph IPA | Unicode
-- | --
ɔ | "0254
Ɔ | "0186
ɛ | "025B
Ɛ | "0190
ɲ | "0272
Ɲ | "019D

https://fonts.google.com/specimen/Balsamiq+Sans?preview.text=M%C9%94g%C9%94k%C9%94r%C9%94w%20ka%C9%B2i%20ka%20k%C9%9B%20ni%20%C5%8Bania%20%C9%B2uman%20ye&preview.text_type=custom#standard-styles

Any possiblity of getting an adjustment made?   This would be awesome for the some 30 million people here that have as I can find, 40 Google web fonts they can use without substitution happening.

Thanks!!!!

**Comment by MartinZaske** [comment]
Please look also at issue #6, they seem to be related.

I do give my +1 for ɛ Ɛ and ɔ Ɔ.

And it would be great, if somebody who understands about the tech here would look into the cause of this, as more glyphs also seem to be affected. Thank you.

**Comment by jibbajabba** [comment]
Issue fixed and delivered.

**Comment by boydkelly** [comment]
Awesome!   Thank you so much!

**Comment by MartinZaske** [comment]
I thank you also. 

Documentation is saying "If you feel your font project has hit a milestone, you must create a new release for it." For our language, this would be a major milestone, because it would allow us to start using balsamiq. I just checked on Google Fonts, and I still see an older version with the capitals in the wrong places.

So just saying, I encourage you to trigger a release please.

**Comment by MartinZaske** [comment]
The changes have now arrived on Google Fonts, this is so nice. Thank you again and please greet the entire team, if you ever meet them. This font-family is muchly appreciated, now that we can use it for our language!
